# Generated by Django 5.2.6 on 2025-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='testimonials/')),
                ('featured', models.BooleanField(default=True)),
            ],
        ),
    ]
