# Generated by Django 5.2.6 on 2025-10-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
