# Generated by Django 5.2.6 on 2025-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_annual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
